os: linux
language: php
dist: xenial
cache:
  directories:
    - $HOME/.composer/cache
jobs:
  include:
    - php: 5.3
      dist: precise
      git:
        depth: false
  fast_finish: true
install:
  - test -f composer.lock && rm composer.lock || true
  - ./composer update --ansi --prefer-dist --no-interaction --optimize-autoloader --no-suggest --no-progress $COMPOSER_ADDITIONAL_FLAGS
before_install:
  - phpenv config-rm xdebug.ini
  - php -r '$cert_locations = openssl_get_cert_locations(); echo $cert_locations["ini_cafile"], " ", $cert_locations["default_cert_file"], PHP_EOL;'
script:
  - ./vendor/bin/phpunit
